### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by vamsisasee** [thechosentom/LumberSnake#1]
Begin Processing ...
Checking Log Dump for files ...
Cleaning all files in filepath .\Log Dump\
worker1.zip
worker2.zip
failed on tabadminservice/inprogress_remote_logs.zip
[Errno 2] No such file or directory: './Log Dump/tabadminservice/inprogress_remo
te_logs.zip'
Successfully extracted worker1.zip!
Successfully extracted worker2.zip!
.\Log Dump\worker1.zip has no data!
.\Log Dump\worker2.zip has no data!
qp-batch processed ...
Traceback (most recent call last):
  File "LumberSnake20181.py", line 204, in <module>
  File "LumberSnake20181.py", line 122, in get_merged
IndexError: list index out of range
[11628] Failed to execute script LumberSnake20181

Getting the above issue when ran using the lumbersnake 2018.1.1 exe.

**Comment by thechosentom** [comment]
This feels like it failed to find any VizQL files in the .zip. It could have been an issue with the two parallel version. This should now be resolved with a singular version for easier clarity.
