### ISSUE TITLE
ImportError: No module named tkinter

### ISSUE THREAD

**Issue by vamsisasee** [thechosentom/LumberSnake#2]
Traceback (most recent call last):
  File "E:\LumberSnake\LumberSnake (2018.1.1).py", line 18, in <module>
    from tkinter import Tk
ImportError: No module named tkinter

![image](https://user-images.githubusercontent.com/14211621/45683625-c5d39600-bb61-11e8-8487-ec675135b06c.png)

**Comment by vamsisasee** [comment]
The issue seems to be with the python version. In 2.7 the module is **Tkinter** and not **tkinter**

You can fix this issue by editing the file LumberSnake (2018.1.1).py line #18 as below

![image](https://user-images.githubusercontent.com/14211621/45683764-12b76c80-bb62-11e8-8729-fef74d47039e.png)

After fixing the above issue, you may get an issue as below

**ImportError: No module named filedialog**

**Comment by christianmatei** [comment]
Also, to add: C:\Users\username\Desktop\TEst
C:\Users\cmatei\Desktop\TEst
Traceback (most recent call last):
  File "C:\Users\User\Desktop\TEst\LumberSnake pre-2018.2.py", line 19, in <module>
    from Tkinter.filedialog import askopenfilename
ImportError: **No module named filedialog**

**Comment by thechosentom** [comment]
Resolved in the latest version. Please use Python 3.7.3 moving forward.
