### ISSUE TITLE
Python 2 and Python 3 inconsistencies

### ISSUE THREAD

**Issue by alexlokhov** [thechosentom/LumberSnake#4]
Hi Tom, I was trying to run the non-compiled version of LumberSnake.

It looks like you are using a mixture of Python 2 and Python 3 syntax which means the scripts wouldn't run in either Python 2 or Python 3 correctly. Both LumberSnake 2018.2.0.py and LumberSnake pre-2018.2.py have this problem.

Looking at LumberSnake 2018.2.0.py:

Sometimes you are using print() with brackets (line 23, 32, 36, 38) - this is Python 3 syntax. Sometimes you are using print without brackets (line 67) - this is Python 2.

```python
from tkinter import Tk
```
- this is a Python 2 module, fails to run under Python 3.

```python
sys.setdefaultencoding('utf-8')
```
- this is a Python 2 function, fails to run under Python 3.

I believe that the previous three issues: https://github.com/thechosentom/LumberSnake/issues/1, https://github.com/thechosentom/LumberSnake/issues/2, https://github.com/thechosentom/LumberSnake/issues/3 are related to this. Maybe you could standardise on Python3 and make it a prerequisite.

**Comment by christianmatei** [comment]
I have some of the issues especially with tkinter
presenting error, while I double checked the libraries etc

**Comment by thechosentom** [comment]
The inconsistencies should have been resolved in this version (thanks for the assistance Alex!).
