### ISSUE TITLE
JSON file is too large

### ISSUE THREAD

**Issue by ghost** [thechosentom/LumberSnake#5]
Hi,

We are currently trying to run the new Lumbersnake with the JSON files but we seem to get the message within Tableau that the JSON files are to large.

![image](https://user-images.githubusercontent.com/14273560/62612706-37e2d400-b908-11e9-9519-95f94f3a2c44.png)

Is there a way to fix this with the Tool automatically without having to change the workbook and or load the data into csv's / Database.

**Comment by thechosentom** [comment]
Hey Jason, there's a new version (see Hyper API) that removes the JSON limitation. The code is here but may need to use the .exe file until the API is officially released.
