### ISSUE TITLE
Multi-line queries no longer supported in Tableau Hyper API 0.0.9273

### ISSUE THREAD

**Issue by pks-biz** [thechosentom/LumberSnake#6]
Multi-line queries are no longer supported in Tableau Hyper API 0.0.9273 leading to errors when calling multi-line queries with the connection object. I get the following error when running the lumbersnake code. Separating the connection queries into separate calls works instead.
![image (1)](https://user-images.githubusercontent.com/56247907/71623037-041b8a00-2bda-11ea-88b3-4a31ef0bea91.png)

**Comment by thechosentom** [comment]
Thank you for forking and fixing! Merged back into main.
